AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda_api_funcionarios

  Powertools for AWS Lambda (Python) example

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: python3.12
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  LambdaFuncionarios:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Description: CRUD de Funcionários com Powertools
      CodeUri: ./app/
      Architectures:
        - x86_64
      Tracing: Active

      # Define três endpoints REST para a mesma função
      Events:
        ListarFuncionarios:
          Type: Api
          Properties:
            Path: /funcionarios
            Method: GET

        CriarFuncionario:
          Type: Api
          Properties:
            Path: /funcionarios
            Method: POST

        AtualizarFuncionario:
          Type: Api
          Properties:
            Path: /funcionarios/{funcionario_id}
            Method: PATCH

      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: lambda_api_funcionarios
          POWERTOOLS_METRICS_NAMESPACE: Powertools
          LOG_LEVEL: INFO

      Tags:
        LambdaPowertools: python